name: Dev Environment Build and Test
on:
  push:
    branches:
      - dev
jobs:
  build-react-frontend:
    name: Build Frontend and Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Prettier
        id: prettier-run
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
          config_path: ./frontend/src/.prettierrc

      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "There were some files that were not formatted."

      - name: Use Node v.20.5.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.5.0

      - name: Install Node Packages
        working-directory: ./frontend
        run: npm install --ignore-engines

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test --passWithNoTests

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [ '6.0' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2


      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-root-username: ${{ secrets.MONGO_DB_USERNAME }}
          mongodb-root-password: ${{ secrets.MONGO_DB_PASSWORD }}
          mongodb-cluster: ${{ secrets.MONGO_DB_CLUSTER }}

      - name: Build and Test Project with Maven
        run: mvn -B package --file pom.xml
        env:
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_USER: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_CLUSTER: ${{ secrets.MONGO_DB_CLUSTER }}

      - name: Run Maven Install
        run: mvn clean install
        env:
          MONGO_DB: ${{ secrets.MONGO_DB }}
          MONGO_USER: ${{ secrets.MONGO_DB_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_DB_PASSWORD }}
          MONGO_CLUSTER: ${{ secrets.MONGO_DB_CLUSTER }}