name: Master Environment Build and Test
on:
  push:
    branches:
      - master
permissions:
  id-token: write
  contents: read

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node v20.5.0
        uses: actions/setup-node@v1
        with:
          node-version: v20.5.0

      - name: Install Npm Packages
        working-directory: ./frontend
        run: npm install --ignore-engines

      - name: Test Frontend
        working-directory: ./frontend
        run: npm run test --passWithNoTests

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test Project with Maven
        run: mvn -B package --file pom.xml

      - name: Run Maven Install
        run: mvn clean install
